### ISSUE TITLE
Only load icons used instead of all icons

### ISSUE THREAD

**Issue by DarkIntaqt** [DarkIntaqt/challenges#93]
Reduce package size by 100kb

**Comment by BlossomiShymae** [comment]
Are the icons you mentioned part of the FontAwesome .woff files used here?

![image](https://user-images.githubusercontent.com/87099578/218923816-0e0c04d5-9329-40e1-9059-36071115b894.png)

I looked into how FontAwesome works and I don't think it is possible to reduce package size when the web fonts route. I think it has to be done by using FontAwesome NPM package along with tree-shaking to reduce the package size. Then only the icons used will be loaded instead of all of them. •ᴗ•

**Comment by DarkIntaqt** [comment]
Planned for #136 , implemented that change already
